[versions]
java = "17"
junit = "5.12.2"
logback = "1.5.0"
google-guice = "7.0.0"
jetty = "11.0.0"

# plugins
shadow = "8.1.1"
jacoco = "0.8.13"

[libraries]
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }

junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version = "6.0.2" }

logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
google-guice = { group = "com.google.inject", name = "guice", version.ref = "google-guice" }

jetty-server = { group = "org.eclipse.jetty", name = "jetty-server", version.ref = "jetty" }
jetty-servlet = { group = "org.eclipse.jetty", name = "jetty-servlets", version.ref = "jetty" }
jetty-ws-server = { group = "org.eclipse.jetty.websocket", name = "websocket-jetty-server", version.ref = "jetty" }
jetty-ws-client = { group = "org.eclipse.jetty.websocket", name = "websocket-jetty-client", version.ref = "jetty" }

[bundles]
test-implementation = ["junit-api", "junit-params"]
test-runtime = ["junit-engine", "junit-platform-launcher"]
jetty = ["jetty-server", "jetty-servlet", "jetty-ws-server"]

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
jacoco = { id = "jacoco", version.ref = "jacoco" }
